name: ft_vox

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: zsh
      run: brew install zsh
    - name: linter_install
      run: ./install_linter.sh ; source ~/.zshrc
    - name: configure
      run: ./configure.sh
    - name: make check
      run: make check
